default_language_version:
  python: python
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [ "--maxkb=10000" ]
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        args: [ "--autofix", "--indent 2", ]

  # Bot
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ "--config", "./bot/pyproject.toml", . ]
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        args: [ "--fix", "--exit-non-zero-on-fix" ]
