version: '3.8'
services:
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
