version: '3.8'
services:
  # PostgreSQL database service
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Bot application service
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-data:
