version: '3.8'
services:
  # PostgreSQL database service
  postgres:
    image: postgres:15.4-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis server service
  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "6379:6379"

  # Bot application service
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
