[tool.poetry]
name = "aiogram-starter-kit"
version = "0.1.0"
description = "Aiogram Starter Kit."
authors = [
  "Serhii Ihnatiev <141933729+iamihnatiev@users.noreply.github.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
aiogram = "^3.0.0rc2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
