version: '3.9'
name: 'aiogram-starter-kit'

# Configurations shared between services
x-base-conf: &base-conf
  env_file:
    - ../.env

services:
  # PostgreSQL database service
  database:
    <<: *base-conf
    image: postgres:15.4-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  # Adminer service for managing databases
  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - '8080:8080'

  # Redis server service
  redis:
    <<: *base-conf
    build:
      context: redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data:rw

  # Bot application service
  bot:
    <<: *base-conf
    build:
      context: ..
      dockerfile: docker/images/bot/Dockerfile
    restart: always
    depends_on:
      - database
      - redis

volumes:
  database_data:
  redis_data:
