version: '3.9'
name: 'aiogram_starter_kit'

services:
  # Bot application service
  bot:
    build:
      context: ..
      dockerfile: docker/images/bot/Dockerfile
    env_file:
      - ../bot/.env
    depends_on:
      - postgres-db
      - redis-db

  # PostgreSQL database service
  postgres-db:
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  # Redis server service
  redis-db:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data:rw

  # Adminer service for managing databases
  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'

volumes:
  postgres_data:
  redis_data:
